# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Kuberentes (k8s) cli - kubectl
      uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
        with:
          args: get nodes


#  # This workflow contains a single job called "build"
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: docker login
#        run: |
#          echo ${{secrets.GITHUB_TOKEN}} | docker login docker.pkg.github.com -u teundeclercq --password-stdin
#
#      - name: docker build AuthServer
#        run: |
#          docker build ./AuthenticationService -t docker.pkg.github.com/teundeclercq/youtubeimgurbackend/authserver:0.0.1
#
#      - name: docker build ImageServer
#        run: |
#          docker build ./ImageService -t docker.pkg.github.com/teundeclercq/youtubeimgurbackend/imageserver:0.0.1
#
#      - name: docker push
#        run: |
#          docker push docker.pkg.github.com/teundeclercq/youtubeimgurbackend/authserver:0.0.1
#          docker push docker.pkg.github.com/teundeclercq/youtubeimgurbackend/imageserver:0.0.1
