apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authservice-ingres
spec:
  rules:
    - host: authservice.youtubeimgurbackend.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authservice-loadbalancer
                port:
                  number: 3001

