apiVersion: v1
kind: Service
metadata:
  name: authservice-loadbalancer
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: authservice-app
  type: LoadBalancer
