apiVersion: v1
kind: Service
metadata:
  name: authservice-service
  labels:
    app: authservice-app
spec:
  type: ClusterIP
  selector:
    app: authservice-app
  ports:
    - protocol: TCP
      name: HTTP
      port: 80
      targetPort: 3000
