## todo change this file to deployment for imageservice

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deploy
  labels:
    app: authservice-app
spec:
  selector:
    matchLabels:
      app: authservice-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: authservice-app
    spec:
      containers:
        - name: authservice-app
          image: ghcr.io/teundeclercq/youtubeimgurbackend/authserver:0.0.3
          imagePullPolicy: Always
          env:
            - name: DB_DATABASE
              value: 'postgresdb'
            - name: DB_USER
              value: 'postgresadmin'
            - name: DB_PASSWORD
              value: 'admin123'
            - name: DB_HOST
              value: '192.168.178.100'
            - name: DB_PORT
              value: '31898'
            - name: TOKEN_SECRET
              value: 'secrettokenforjwttokens'
          ports:
            - containerPort: 3001
#          command:
#            - "/bin/sh"
#            - "-c"
#            - "sleep 36000"
#          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "10m"
#            limits:
#              memory: "256Mi"
#              cpu: "500m"
      imagePullSecrets:
      - name: regcred
